Add ajax views for retrieving sidebar and user dropdown links
bihealth/sodar-core pull request #1420
Opened 2024-04-25 10:14 UTC by gromdimon

Issue: #1366

2024-04-25 11:42 UTC, gromdimon commented
- [x] Added ajax views
- [ ] Added urls
- [ ] Added tests
- [ ] Added docstrings for usage

2024-04-25 12:50 UTC, mikkonie requested changes
Good work! I added some requests to remove the `url_name` parameters from Ajax views as they are not necessary.

2024-04-25 12:50 UTC, mikkonie commented on projectroles/views_ajax.py
> +        url_name = request.GET.get('url_name')
As discussed earlier, we can simply omit `url_name` here. By providing the app_name, the client side app can provide the correct app to be highlighted regardless of what page we are.

This will be mostly be used by single-page apps which don't have a concept of multiple separate Django URLs anyway. The URL name is used for `projectroles` URLs since there are multiple UI elements highlighted depending on which projectroles view we are on. These Ajax views are called by other apps.

2024-04-25 12:50 UTC, mikkonie commented on projectroles/views_ajax.py
> +        url_name = request.GET.get('url_name')
Same thing here, we can simply omit `url_name` from the Ajax views.

2024-04-26 10:19 UTC, mikkonie requested changes
Looking good! One more comment regarding permission tests for the ajax views. Once we have permission tests in place, I'll be happy to merge.

2024-04-26 10:19 UTC, mikkonie commented on projectroles/tests/test_views_ajax.py
> +    def test_get_no_access(self):
Permission tests should go in `projectroles.tests.test_permissions_ajax`. Follow the conventions there and, needless to say, ask me if anything is unclear.

2024-04-29 12:42 UTC, mikkonie requested changes
Some cleanup comments, otherwise looking good.

2024-04-29 12:42 UTC, mikkonie commented on projectroles/tests/test_permissions_ajax.py
> +        self.assert_response(self.url, good_users, 200, method='GET')
Since `GET` is the default value for `method` here, we can just omit the parameter here for a bit more compact tests.

2024-04-29 12:42 UTC, mikkonie commented on projectroles/tests/test_permissions_ajax.py
> +        bad_users = [self.user_no_roles, self.user_finder_cat, self.anonymous]
Let's follow the conventions for ordering the users for better readability: first all the users with roles, then user_no_roles, ending with anonymous.

2024-04-29 12:42 UTC, mikkonie commented on projectroles/tests/test_permissions_ajax.py
> +        self.assert_response(self.url, self.user_no_roles, 200, method='GET')
You should add a test case for when the project is archived. See elsewhere in tests for an example. Note that this is only required for the project, as categories can not be archived.

2024-04-29 13:31 UTC, mikkonie approved these changes

2024-04-29 13:52 UTC, merged